var a = new Manga("a", "/imagens/cm1.jpg", "Chainsaw Man", "Tatsuki Fujimoto", "Novo", "1", "29,90", "5,50", "Denji é um jovem extremamente pobre que junto de Pochita, seu demônio de estimação, trabalha feito um condenado como Caçador de Demônios para pagar a imensa dívida que possui. Mas sua vida de miséria está prestes a mudar graças a uma traição brutal!! Aqui começa a história de um novo anti-herói que com um demônio em seu corpo, caça demônios!!", "Não vendido");
var b = new Manga("b", "/imagens/mha28.jpg", "My Hero Academia", "Kohei Horikoshi", "Usado", "28", "12,80", "5,50", "Explode a guerra entre os heróis e a Fronte de Libertação Paranormal. Mirko tenta chegar até o laboratório onde Shigaraki se encontra para tentar impedir que ele alcance a sua forma suprema, mas Midoriya sente que uma presença sinistra está para despertar.", "Não vendido");
var c = new Manga("c", "/imagens/jk3.jpg", "Jujutsu Kaisen", "Gege Akutami", "Novo", "3", "21,30", "5,50", "Aoi Toudou e Mai Zenin, da Escola Técnica Superior de Jujutsu de Kyoto, aparecem diante de Fushiguro e Kugisaki! O que Fushiguro respondeu para Toudou, quando questionado sobre o tipo de garota que ele gosta? Enquanto isso, Itadori é enviado para o local em que um espírito amaldiçoado provocou um incidente, fazendo com que o feiticeiro treine suas habilidades na prática!", "Não vendido");
var d = new Manga("d", "/imagens/sk1.jpg", "Shaman King", "Hiroyuki Takei", "Usado", "1", "12,80", "5,50", "Yoh Asakura é um shaman - um dos poucas pessoas que são dotados desse poder, graças à formação ou talento natural, pode canalizar espíritos que a maioria das pessoas não consegue nem ver. Com a ajuda de sua noiva, Anna, Yoh está em treinamento para o máximo evento Shaman: a luta Shaman em Tóquio, o torneio uma vez a cada 500 anos para ver quem consegue moldar o futuro da humanidade e se tornar o Rei Shaman. Mas, infelizmente para Yoh, cada shaman no mundo está competindo pelo mesmo prêmio...", "Não vendido");
var e = new Manga("e", "/imagens/h1.jpg", "Haikyuu", "Haruichi Furudate", "Novo", "1", "49,90", "5,50", "Shoyo Hinata e Tobio Kageyama, dois garotos fascinados pelo vôlei. A diferença é que Kageyama é um levantador talentoso, e Hinata, um atacante de baixa estatura para um jogador. Os dois se encontram durante a primeira rodada da etapa de classificação para o torneio Nacional, e acabam se tornando grande rivais. Por coincidência do destino, eles terão que unir forças para entrar no clube de vôlei do colégio Karasuno e manter o sonho de continuar jogando vôlei.", "Não vendido");
var f = new Manga("f", "/imagens/ds9.jpg", "Demon Slayer", "Koyoharu Gotouge", "Novo", "9", "19,90", "5,50", "Tanjirou e os outros, juntamente ao “Hashira do Som” – Tengen Usui, se dirigem para o “Distrito dos Prazeres”, local onde onis vivem. As três esposas de Tengen se infiltraram no local para coletar informações, porém, perderam contato com ele. Tanjirou e os meninos se infiltram disfarçados de mulheres, mas não conseguem descobrir onde os onis estão localizados. Mas as oirans estão nas mãos do inimigo? Conseguirá Tanjirou encontrar os vilões?!", "Não vendido");
var g = new Manga("g", "/imagens/w1.jpg", "Wotakoi", "Fujita", "Novo", "1", "16,90", "5,50", "Apesar de Narumi Momose esconder seu gosto por histórias yaoi, seu namorado descobre tal hobby e termina o relacionamento. Para renovar sua vida, ela decide mudar de trabalho e lá acaba encontrando seu amigo de infncia, Hirotaka Nifuji, um viciado em video games, que por pouco não revela o segredo de sua amiga. Então, ela decide sugerir um plano para que ele nunca mais fale sobre o assunto, mas não contava com uma contraproposta: por que não começarem a namorar? Obcecados por seus interesses pessoais, será difícil para eles manterem um relacionamento.", "Não vendido");
var h = new Manga("h", "/imagens/jk4.jpg", "Jujutsu Kaisen", "Gege Akutami", "Usado", "4", "12,80", "5,50", "Itadori investiga os assassinatos causados por uma maldição e acaba conhecendo Junpei, um garoto que é fascinado por Mahito, o responsável pelas mortes. Qual será a reação de Itadori ao ver o novo amigo transformado em fantoche da maldição?", "Não vendido");
var i = new Manga("i", "/imagens/ds7.jpg", "Demon slayer", "Koyoharu Gotouge", "Novo", "7", "19,90", "5,50", "Com a ajuda de Shinobu Kochou, um dos Hashira, Tanjirou e os outros se recuperaram de suas feridas e aprenderam o Foco Absoluto Constante. Para a próxima missão, eles embarcam no “Trem Infinito”, com o Hashira das Chamas, para exterminar um oni. Porém, o oni prende Tanjirou e seus amigos dentro do mundo dos sonhos!! Como sair dessa situação?!", "Não vendido");
var j = new Manga("j", "/imagens/cm2.jpg", "Chainsaw Man", "Tatsuki Fujimoto", "Novo", "2", "29,90", "5,50", "Motivado por um desejo avassalador, Denji encara o Demônio dos Morcegos em uma batalha mortal!! Será que ele conseguirá alcançar seu objetivo no fim?! Ou então...?! E quem é o Demônio das Armas de Fogo, o inimigo da humanidade de que Makima falou?! A luta de Denji, o cãozinho da Segurança Pública, ruma para novos desdobramentos!!", "Não vendido");
var k = new Manga("k", "/imagens/ds11.jpg", "Demon Slayer", "Koyoharu Gotouge", "Novo", "11", "24,90", "5,50", "A dura batalha no Distrito das Flores contra os irmãos Gyuutarou e Daki, os sextos Jougen, ainda continua. Embora Tanjirou e os outros estejam lutando em conjunto, Uzui, Inosuke e Zenitsu caem diante da lâmina do inimigo. Agora que seus amigos foram derrotados, conseguirá Tanjirou acabar com os dois onis sozinho?!");
var l = new Manga("l", "/imagens/ng1.jpg", "Naruto Gold", "Masashi Kishimoto", "Novo", "1", "18,90", "5,50", "Esta é a Vila Oculta da Folha. Naruto é o garoto mais problemático da Academia Ninja e está sempre aprontando todas!! Seu grande sonho é se tornar um shinobi digno do título de Hokage, o mais forte e respeitado ninja da vila, e superar todos os Hokages anteriores...!! Mas um segredo em torno de seu nascimento o mantém distante tanto de seu sonho quanto das pessoas...!! Não perca mais uma chance de acompanhar a empolgante jornada de Naruto, o garoto ninja que conquistou o mundo inteiro, nesta nova edição de luxo com pôsteres, freetalks exclusivos do autor e muito mais!");
var m = new Manga("m", "/imagens/sxf5.jpg", "Spy x Family", "Tatsuya Endou", "Novo", "5", "29,90", "5,50", "O cão clarividente Bond se junta à família, e parecia que tanto os Forger quanto a Operação Strix entravam nos eixos... mas eis que Anya se vê no maior apuro de sua vida com a chegada dos exames parciais!! Como terminarão essas tumultuadas provas, que podem render stellas ou tonitrus...?!");
var n = new Manga("n", "/imagens/jk2.jpg", "Jujutsu Kaisen", "Gege Akutami", "Usado", "2", "12,80", "5,50", "Um útero amaldiçoado surge repentinamente em um reformatório. Itadori e seus colegas do primeiro ano foram designados para salvar as pessoas que não conseguiram fugir do edifício! Mas o grupo depara-se com uma situação desesperadora: o útero se transformou em um espírito amaldiçoado de nível especial. Itadori tenta revidar, trocando de corpo com Sukuna, mas será que o plano vai dar certo?!");
var o = new Manga("o", "/imagens/uvi1.jpg", "Uma Vida Imortal", "Yoshitoki Oima", "Novo", "1", "26,90", "5,50", "Um ser imortal é enviado para a superfície da Terra sem qualquer conhecimento ou sequer um “eu”. Além de sua imortalidade, ele tem a capacidade de tomar a “vontade” e a forma aqueles que morreram à sua volta. E com esses poderes e experiências, esse ser passa a entender e explorar o mundo, procurando sua razão de existir e a verdade por trás de tudo. Fumetsu no Anata E / To Your Eternity");
var p = new Manga("p", "/imagens/ds10.jpg", "Demon Slayer", "Koyoharu Gotouge", "Novo", "10", "22,90", "5,50", "A Oiran Warabihime é a oni que controla todo o distrito das flores! Ao se juntar à parte de seu corpo que estava dividida, ela fica ainda mais poderosa e ataca Tanjirou com todas as suas forças!! Nosso herói recorre à Hinokami Kagura, mas parece que está prestes a exceder seu limite!! Nezuko e Uzui aparecem para lutar no lugar de Tanjirou, mas a batalha toma rumos inesperados!!");
var q = new Manga("q", "/imagens/ng2.jpg", "Naruto Gold", "Masashi Kishimoto", "Usado", "2", "12,80", "5,50", "Naruto, Sasuke e Sakura são testados por Kakashi-sensei!! Se passarem nessa difícil prova, eles se tornarão Genins – ninjas aprendizes! A Equipe Sete parte para assegurar a proteção de um notável construtor de pontes, o senhor Tazuna, mas sinistras sombras assassinas os espreitam!");
var r = new Manga("r", "/imagens/ds6.jpg", "Demon Slayer", "Koyoharu Gotouge", "Novo", "6", "22,90", "5,50", "Tanjirou derrota o oni-aranha... Porém, ele e Nezuko são capturados por Shinobu Kochou, que também é membro do Kisatsutai. Ele é levado para o quartel general do esquadrão, e é colocado diante dos Hashiras, os pilares da organização, para ser julgado por seus atos. Todos os Hashiras são contra o fato de Tanjirou andar com uma oni, mesmo sendo sua irmã mais nova, e resolvem puni-lo. Porém, quando isso ia acontecer, uma figura importante dá as caras...!!");
var s = new Manga("s", "/imagens/ds12.jpg", "Demon slayer", "Koyoharu Gotouge", "Usado", "12", "12,80", "5,50", "Pela primeira vez, em 113 anos, um jougen foi derrotado, e isso só causa tensão entre a alta cúpula dos doze Kizuki. Do lado dos humanos, Haganezuka está furioso com Tanjirou, que quebrou sua espada na luta contra Gyuutarou. Agora, nosso herói partirá em uma viagem para conseguir consertá-la.");
var t = new Manga("t", "/imagens/biy2.jpg", "Bloom Into You", "Nio Nakatani", "Novo", "2", "27,50", "5,50", "Touko Nanami se tornou presidente do novo Conselho Estudantil que começa a entrar em ação. Yuu Koito torna-se membro do Conselho e, apesar de aceitar os sentimentos de Touko, sofre por ainda não sentir nada especial dentro de si. \"Eu também quero gostar de você, Nanami-senpai\", pensou Yuu. Porém...");

var mangas = [a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t];
var mangasProdutos = [];

function Manga(id, foto, titulo, autor, tipo, volume, preco, frete, detalhes, vendido) {
    this.id = id;
    this.foto = foto;
    this.titulo = titulo;
    this.autor = autor;
    this.tipo = tipo;
    this.volume = volume;
    this.preco = preco;
    this.frete = frete;
    this.detalhes = detalhes;
    this.vendido = vendido;
}
